/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackageKSK;

import DVHC.*;
import DataDB2.FillData;
import DataDB2.IntegerRenderer;
import KhamSucKhoe.*;
import com.sun.glass.events.KeyEvent;
import java.awt.Frame;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author bvndc
 */
public class JDialogGiayDK extends javax.swing.JDialog {

    /**
     * Creates new form JDialogGiayDK
     */
    ActionLyDo actLD = new ActionLyDo();
    ActionDVHC actDVHC = new ActionDVHC();
    ActionGiayKSK actKSK = new ActionGiayKSK();
    ActionQuocGia actQG = new ActionQuocGia();
    ActionChiPhi actCP = new ActionChiPhi();
    ActionGiaVP actGiaVP = new ActionGiaVP();
    ActionGoiGiaVP actGoi = new ActionGoiGiaVP();

    String maXP;
    String quocGiaID;
    private String soKSK;
    String giaVPID;
    Float donGia;
    ArrayList<LyDo> lstLD;

    public JDialogGiayDK(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlDichVu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtTenGiaVP = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        chkPrintAll = new javax.swing.JCheckBox();
        pnlThongTinDK = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtQuocGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboLyDo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamSinh = new javax.swing.JSpinner();
        txtDiaChi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSoKSK = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox();
        txtHoTen = new javax.swing.JTextField();
        txtCapNgay = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        btnQuocGia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKetQua = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtNgay = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng ký khám sức khoẻ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/NewDocumentHS.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/saveHS.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/GoToParentFolderHS.png"))); // NOI18N
        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        pnlDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dịch vụ đi kèm:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setText("Tên dịch vụ:");

        txtTenGiaVP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenGiaVPFocusLost(evt);
            }
        });

        txtSoLuong.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/AddTableHS.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });

        btnSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/RightsRestrictedHS.png"))); // NOI18N
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        jLabel13.setText("Số lượng:");

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/PrintHS.png"))); // NOI18N

        chkPrintAll.setSelected(true);
        chkPrintAll.setText("In tất cả DV");

        javax.swing.GroupLayout pnlDichVuLayout = new javax.swing.GroupLayout(pnlDichVu);
        pnlDichVu.setLayout(pnlDichVuLayout);
        pnlDichVuLayout.setHorizontalGroup(
            pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDichVuLayout.createSequentialGroup()
                        .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenGiaVP)
                            .addGroup(pnlDichVuLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDichVuLayout.createSequentialGroup()
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDichVuLayout.createSequentialGroup()
                                .addComponent(btnPrint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSub))
                            .addComponent(chkPrintAll))))
                .addContainerGap())
        );
        pnlDichVuLayout.setVerticalGroup(
            pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDichVuLayout.createSequentialGroup()
                .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(chkPrintAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrint)
                    .addGroup(pnlDichVuLayout.createSequentialGroup()
                        .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addGroup(pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenGiaVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        pnlThongTinDK.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin đăng ký:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel8.setText("Địa chỉ:");

        txtQuocGia.setText("Việt nam");
        txtQuocGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuocGiaFocusLost(evt);
            }
        });

        jLabel10.setText("Quốc gia làm việc");

        cboLyDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Phái:");

        jLabel11.setText("Kết quả khám:");

        jLabel9.setText("Lý do KSK:");

        jLabel7.setText("Cấp ngày:");

        txtNamSinh.setEditor(new javax.swing.JSpinner.NumberEditor(txtNamSinh, "####"));

        txtDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusLost(evt);
            }
        });

        jLabel2.setText("Ngày ĐK:");

        jLabel1.setText("Số đăng ký:");

        txtSoKSK.setEditable(false);
        txtSoKSK.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtSoKSK.setForeground(java.awt.Color.red);
        txtSoKSK.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Số CMND:");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nữ", "Nam" }));

        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoTenKeyTyped(evt);
            }
        });

        txtCapNgay.setDateFormatString("dd/MM/yyyy");

        jLabel3.setText("Họ và tên:");

        btnQuocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/OrganizerHS.png"))); // NOI18N
        btnQuocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuocGiaActionPerformed(evt);
            }
        });

        txtKetQua.setColumns(20);
        txtKetQua.setRows(5);
        jScrollPane1.setViewportView(txtKetQua);

        jLabel4.setText("Năm sinh:");

        txtNgay.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout pnlThongTinDKLayout = new javax.swing.GroupLayout(pnlThongTinDK);
        pnlThongTinDK.setLayout(pnlThongTinDKLayout);
        pnlThongTinDKLayout.setHorizontalGroup(
            pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinDKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinDKLayout.createSequentialGroup()
                        .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen)
                            .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinDKLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtCapNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlThongTinDKLayout.createSequentialGroup()
                                .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cboLyDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(txtDiaChi)
                    .addGroup(pnlThongTinDKLayout.createSequentialGroup()
                        .addComponent(txtSoKSK, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlThongTinDKLayout.createSequentialGroup()
                        .addComponent(txtQuocGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuocGia)))
                .addContainerGap())
        );
        pnlThongTinDKLayout.setVerticalGroup(
            pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinDKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtSoKSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(txtCapNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuocGia)
                    .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinDKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongTinDK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtSoKSK.setText("");
        txtNgay.setDate(Date.valueOf(LocalDate.now()));
        txtCapNgay.setDate(Date.valueOf(LocalDate.now()));
        txtNamSinh.setValue(LocalDate.now().getYear());
        txtHoTen.setText("");
        txtSoCMND.setText("");
        txtDiaChi.setText("");
        txtQuocGia.setText("");
        txtKetQua.setText("");
        quocGiaID = "VN";
        txtQuocGia.setText("Việt nam");
        txtHoTen.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            btnNewActionPerformed(null);
            loadLyDo();
            showGiayKSK();
            showChiPhi();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtDiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusLost
        try {
            if (txtDiaChi.getText().trim().length() == 0) {
                maXP = "";
                return;
            }
            ResultSet rs = actDVHC.getAllDVHC(txtDiaChi.getText());
            rs.last();
            if (rs.getRow() > 0) {
                if (rs.getRow() > 1) {
                    JDialogSearchDVHC frm = new JDialogSearchDVHC((Frame) this.getParent(), true);
                    rs.first();
                    frm.showData(rs);
                    frm.setVisible(true);
                    rs.absolute(frm.getIndexSelected() + 1);
                    rs.next();
                } else {
                    rs.first();
                }
                txtDiaChi.setText(rs.getString("TenDVHC"));
                maXP = rs.getString("MaXP");
            } else {
                maXP = "";
                txtDiaChi.setText("");
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtDiaChiFocusLost

    private void txtHoTenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_txtHoTenKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if (!kiemTra()) {
                return;
            }
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            GiayKSK giayKSK = new GiayKSK(txtSoKSK.getText(),
                    Date.valueOf(LocalDate.parse(df.format(txtNgay.getDate()), DateTimeFormatter.ofPattern("dd/MM/yyyy"))),
                    txtHoTen.getText(),
                    (int) txtNamSinh.getValue(),
                    cboGioiTinh.getSelectedIndex(),
                    txtSoCMND.getText(),
                    Date.valueOf(LocalDate.parse(df.format(txtCapNgay.getDate()), DateTimeFormatter.ofPattern("dd/MM/yyyy"))),
                    maXP,
                    lstLD.get(cboLyDo.getSelectedIndex()).getLyDoID(),
                    quocGiaID, null, txtKetQua.getText());
            txtSoKSK.setText(actKSK.saveGiayKSK(giayKSK));
            saveDichVu();
            btnNew.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtQuocGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuocGiaFocusLost
        try {
            if (txtQuocGia.getText().trim().length() == 0) {
                quocGiaID = "";
                return;
            }
            ResultSet rs = actQG.getQuocGia(txtQuocGia.getText());
            rs.last();
            if (rs.getRow() > 0) {
                if (rs.getRow() > 1) {
                    JDialogSearchQuocGia frm = new JDialogSearchQuocGia((Frame) this.getParent(), true);
                    frm.setQuocGiaID(txtQuocGia.getText());
                    frm.setVisible(true);
                    quocGiaID = frm.getQuocGiaID();
                    txtQuocGia.setText(frm.getTenQuocGia());
                } else {
                    rs.first();
                    quocGiaID = rs.getString("QuocGiaID");
                    txtQuocGia.setText(rs.getString("TenQuocGia"));
                }
            } else {
                quocGiaID = rs.getString("QuocGiaID");
                txtQuocGia.setText(rs.getString("TenQuocGia"));
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtQuocGiaFocusLost

    private void btnQuocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuocGiaActionPerformed
        JDialogSearchQuocGia frm = new JDialogSearchQuocGia((Frame) this.getParent(), true);
        frm.setVisible(true);
        quocGiaID = frm.getQuocGiaID();
        txtQuocGia.setText(frm.getTenQuocGia());
    }//GEN-LAST:event_btnQuocGiaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            btnSaveActionPerformed(null);
            ChiPhi chiPhi = new ChiPhi(txtSoKSK.getText(), giaVPID, Integer.parseInt(txtSoLuong.getValue().toString()), donGia);
            actCP.saveChiPhi(chiPhi);
            showChiPhi();
            txtTenGiaVP.setText("");
            txtTenGiaVP.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtTenGiaVPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenGiaVPFocusLost
        try {
            if (txtTenGiaVP.getText().trim().length() == 0) {
                giaVPID = "";
                return;
            }
            ResultSet rs = actGiaVP.getListGiaVP(txtTenGiaVP.getText());
            rs.last();
            if (rs.getRow() > 0) {
                if (rs.getRow() > 1) {
                    JDialogSearchGiaVP frm = new JDialogSearchGiaVP((Frame) this.getParent(), true);
                    frm.setGiaVPID(txtTenGiaVP.getText());
                    rs.first();
                    frm.setVisible(true);
                    giaVPID = frm.getGiaVPID();
                    txtTenGiaVP.setText(frm.getTenGiaVP());
                    donGia = frm.getGiaTH();
                } else {
                    rs.first();
                    giaVPID = rs.getString("GiaVPID");
                    txtTenGiaVP.setText(rs.getString("TenGiaVP"));
                    donGia = rs.getFloat("GiaTH");
                }
            } else {
                giaVPID = "";
                txtTenGiaVP.setText("");
                donGia = null;
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtTenGiaVPFocusLost

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            actCP.deleteChiPhi(txtSoKSK.getText(), jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            showChiPhi();
        }
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAddActionPerformed(null);
        }
    }//GEN-LAST:event_btnAddKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGiayDK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGiayDK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGiayDK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGiayDK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGiayDK dialog = new JDialogGiayDK(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnQuocGia;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSub;
    private javax.swing.JComboBox cboGioiTinh;
    private javax.swing.JComboBox cboLyDo;
    private javax.swing.JCheckBox chkPrintAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlDichVu;
    private javax.swing.JPanel pnlThongTinDK;
    private com.toedter.calendar.JDateChooser txtCapNgay;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextArea txtKetQua;
    private javax.swing.JSpinner txtNamSinh;
    private com.toedter.calendar.JDateChooser txtNgay;
    private javax.swing.JTextField txtQuocGia;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtSoKSK;
    private javax.swing.JSpinner txtSoLuong;
    private javax.swing.JTextField txtTenGiaVP;
    // End of variables declaration//GEN-END:variables

    private void loadLyDo() {
        try {
            lstLD = actLD.getAllLyDo();
            cboLyDo.removeAllItems();
            for (LyDo ld : lstLD) {
                cboLyDo.addItem(ld.getTenLyDo());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean kiemTra() {
        if (txtNgay.getDate().compareTo(Date.valueOf(LocalDate.now())) > 0) {
            JOptionPane.showMessageDialog(null, "Ngày đăng ký sai!");
            txtNgay.requestFocus();
            return false;
        }
        if (txtHoTen.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập họ và tên!");
            txtHoTen.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtNamSinh.getValue().toString()) > LocalDate.now().getYear()) {
            JOptionPane.showMessageDialog(null, "Năm sinh sai!");
            txtNamSinh.requestFocus();
            return false;
        }
        if (txtCapNgay.getDate().compareTo(Date.valueOf(LocalDate.now())) > 0) {
            JOptionPane.showMessageDialog(null, "Ngày cấp CMND sai!");
            txtCapNgay.requestFocus();
            return false;
        }
        if (maXP.trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ!");
            txtDiaChi.requestFocus();
            return false;
        }
        if (quocGiaID.trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa nhập Quốc gia!");
            txtQuocGia.requestFocus();
            return false;
        }

        return true;
    }

    public String getSoKSK() {
        return soKSK;
    }

    public void setSoKSK(String soKSK) {
        this.soKSK = soKSK;
        txtSoKSK.setText(soKSK);
    }

    private void showGiayKSK() throws SQLException {
        if (getSoKSK() == null) {
            return;
        }
        ResultSet rs = actKSK.getGiayKSK(getSoKSK());
        rs.next();
        txtSoKSK.setText(getSoKSK());
        txtNgay.setDate(rs.getDate("Ngay"));
        txtHoTen.setText(rs.getString("HoTen"));
        txtNamSinh.setValue(rs.getInt("NamSinh"));
        cboGioiTinh.setSelectedIndex(rs.getInt("GioiTinh"));
        txtSoCMND.setText(rs.getString("SoCMND"));
        txtCapNgay.setDate(rs.getDate("CapNgay"));
        maXP = rs.getString("DiaChi");
        txtDiaChi.setText(actDVHC.getTenDVHC(maXP));
        cboLyDo.setSelectedIndex(actLD.getIndexLyDo(lstLD, rs.getString("LyDoID")));
        quocGiaID = rs.getString("QuocGiaID");
        txtQuocGia.setText(actQG.getNameQuocGia(quocGiaID));
        txtKetQua.setText(rs.getString("KetQua"));
    }

    private void showChiPhi() {
        try {
            String[] header = {"Thu", "Mã số", "Nội dung", "Số lượng", "Đơn giá", "Thành tiền"};
            ResultSet rs = actCP.getListChiPhi(txtSoKSK.getText());
            FillData fillData = new FillData();
            fillData.fillDataJTable(jTable1, header, rs);
            TableCellRenderer tcr;
            tcr = new IntegerRenderer();
            jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(5).setCellRenderer(tcr);
            if (jTable1.getRowCount() == 0) {
                jTable1.setAutoResizeMode(1);
            } else {
                jTable1.setAutoResizeMode(0);
            }
        } catch (Exception ex) {
            Logger.getLogger(JDialogGiayDK.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveDichVu() throws SQLException {
        ResultSet rs = actGoi.getListGoiGiaVP(lstLD.get(cboLyDo.getSelectedIndex()).getLyDoID());
        while (rs.next()) {
            try {
                ChiPhi chiPhi = new ChiPhi(txtSoKSK.getText(), rs.getString("GiaVPID"), 1, rs.getFloat("GiaTH"));
                actCP.saveChiPhi(chiPhi);
            } catch (Exception ex) {
                Logger.getLogger(JDialogGiayDK.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        showChiPhi();
    }
}
