/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PackageKSK;

/**
 *
 * @author bvndc
 */
import DataDB2.*;
import KhamSucKhoe.*;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.TableCellRenderer;
public class JInternalFrameListGiayKSK extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameListGiayKSK
     */
    ActionGiayKSK giayKSK = new ActionGiayKSK();
    public JInternalFrameListGiayKSK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuNew = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtDenNgay = new com.toedter.calendar.JDateChooser();
        btnRefresh = new javax.swing.JButton();
        lblTongSo = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        mnuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/AddTableHS.png"))); // NOI18N
        mnuNew.setText("Thêm...");
        mnuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuNew);

        mnuEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/EditTableHS.png"))); // NOI18N
        mnuEdit.setText("Sửa...");
        mnuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuEdit);

        mnuDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/DeleteHS.png"))); // NOI18N
        mnuDelete.setText("Xoá giấy khám sức khoẻ...");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuDelete);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Danh sách khám sức khoẻ");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/GoToParentFolderHS.png"))); // NOI18N
        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ ngày:");

        txtTuNgay.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Đến ngày:");

        txtDenNgay.setDateFormatString("dd/MM/yyyy");

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/RefreshDocViewHS.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblTongSo.setForeground(java.awt.Color.blue);
        lblTongSo.setText("Tổng số: 0");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/EditTableHS.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongSo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(btnRefresh)
                        .addComponent(lblTongSo)
                        .addComponent(btnEdit))
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            String[] header = {"Số KSK", "Ngày", "Họ tên", "Năm sinh", "Phái", "Số CMND", "Cấp ngày", "Địa chỉ", "Lý do", "Quốc gia", "Cơ quan", "Kết quả"};
            FillData fillData = new FillData();
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            ResultSet rs = giayKSK.getGiayKSK(Date.valueOf(LocalDate.parse(df.format(txtTuNgay.getDate()), DateTimeFormatter.ofPattern("dd/MM/yyyy"))),
                                              Date.valueOf(LocalDate.parse(df.format(txtDenNgay.getDate()), DateTimeFormatter.ofPattern("dd/MM/yyyy")))); 
            fillData.fillDataJTable(jTable1, header, rs);
            TableCellRenderer tcr;
            tcr = new DateRenderer();
            jTable1.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(6).setCellRenderer(tcr);
            lblTongSo.setText("Tổng số: " + jTable1.getRowCount());
            if (jTable1.getRowCount() == 0)
                jTable1.setAutoResizeMode(1);
            else
                jTable1.setAutoResizeMode(0);
        } catch (Exception e){
            e.printStackTrace();
        }
                
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        txtTuNgay.setDate(Date.valueOf(LocalDate.now()));
        txtDenNgay.setDate(Date.valueOf(LocalDate.now()));
        btnRefreshActionPerformed(null);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            JDialogGiayDK frm = new JDialogGiayDK(null, true);
            frm.setSoKSK(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            frm.setVisible(true);
            btnRefreshActionPerformed(null);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
        giayKSK.deleteGiayKSK(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        btnRefreshActionPerformed(null);
    }//GEN-LAST:event_mnuDeleteActionPerformed

    private void mnuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewActionPerformed
        JDialogGiayDK frm = new JDialogGiayDK(null, true);
        frm.setVisible(true);
        btnRefreshActionPerformed(null);
    }//GEN-LAST:event_mnuNewActionPerformed

    private void mnuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditActionPerformed
        btnEditActionPerformed(null);
    }//GEN-LAST:event_mnuEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTongSo;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuEdit;
    private javax.swing.JMenuItem mnuNew;
    private com.toedter.calendar.JDateChooser txtDenNgay;
    private com.toedter.calendar.JDateChooser txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
