/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PackageKSK;

import KhamSucKhoe.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
/**
 *
 * @author bvndc
 */
public class MainJFrameKSK extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrameKSK
     */
    public MainJFrameKSK() {
        initComponents();
        Image customIcon = Toolkit.getDefaultToolkit().getImage("MedicalBag.png");
        this.setIconImage(customIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuLogOut = new javax.swing.JMenuItem();
        mnuDoiMK = new javax.swing.JMenuItem();
        mnuCreateUsers = new javax.swing.JMenuItem();
        mnuPhanQuyen = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuQuit = new javax.swing.JMenuItem();
        mnuDanhMuc = new javax.swing.JMenu();
        mnuCoQuan = new javax.swing.JMenuItem();
        mnuLyDo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuQuocGia = new javax.swing.JMenuItem();
        mnuKSK = new javax.swing.JMenu();
        mnuDangKy = new javax.swing.JMenuItem();
        mnuListDK = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuHoanTra = new javax.swing.JMenuItem();
        mnuVienPhi = new javax.swing.JMenu();
        mnuThuPhiKSK = new javax.swing.JMenuItem();
        mnuListDaThu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuThuPhiCQ = new javax.swing.JMenuItem();
        mnuListThuCQ = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuGiaVP = new javax.swing.JMenuItem();
        mnuGoiGiaVP = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuListThuNgan = new javax.swing.JMenuItem();
        mnuBaoCao = new javax.swing.JMenu();
        mnuTKHoanTra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý khám sức khoẻ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 217, 223));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHÁM SỨC KHOẺ");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bệnh viện Nguyễn Đình Chiểu");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(164, 164, 164)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblUserName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblUserName.setForeground(java.awt.Color.red);

        mnuHeThong.setText("Hệ thống");

        mnuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/PrimaryKeyHS.png"))); // NOI18N
        mnuLogOut.setText("Đăng xuất...");
        mnuHeThong.add(mnuLogOut);

        mnuDoiMK.setText("Đổi mật khẩu...");
        mnuHeThong.add(mnuDoiMK);

        mnuCreateUsers.setText("Khai báo người dùng...");
        mnuHeThong.add(mnuCreateUsers);

        mnuPhanQuyen.setText("Phân quyền sử dụng...");
        mnuHeThong.add(mnuPhanQuyen);
        mnuHeThong.add(jSeparator6);

        mnuQuit.setText("Thoát");
        mnuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuitActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuQuit);

        mainMenu.add(mnuHeThong);

        mnuDanhMuc.setText("Danh mục");

        mnuCoQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/List_BulletsHS.png"))); // NOI18N
        mnuCoQuan.setText("Cơ quan, doanh nghiệp...");
        mnuCoQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCoQuanActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuCoQuan);

        mnuLyDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/TaskHS.png"))); // NOI18N
        mnuLyDo.setText("Lý do khám sức khoẻ...");
        mnuLyDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLyDoActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuLyDo);
        mnuDanhMuc.add(jSeparator1);

        mnuQuocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/OrganizerHS.png"))); // NOI18N
        mnuQuocGia.setText("Danh mục Quốc gia...");
        mnuQuocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuocGiaActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuQuocGia);

        mainMenu.add(mnuDanhMuc);

        mnuKSK.setText("Khám sức khoẻ");

        mnuDangKy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/AddTableHS.png"))); // NOI18N
        mnuDangKy.setText("Đăng ký khám...");
        mnuDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangKyActionPerformed(evt);
            }
        });
        mnuKSK.add(mnuDangKy);

        mnuListDK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuListDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/ShowRulelinesHS.png"))); // NOI18N
        mnuListDK.setText("Danh sách đăng ký khám...");
        mnuListDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListDKActionPerformed(evt);
            }
        });
        mnuKSK.add(mnuListDK);
        mnuKSK.add(jSeparator5);

        mnuHoanTra.setText("Cập nhật thông tin KSK hoàn trả...");
        mnuKSK.add(mnuHoanTra);

        mainMenu.add(mnuKSK);

        mnuVienPhi.setText("Viện phí");

        mnuThuPhiKSK.setText("Thu phí khám sức khoẻ...");
        mnuThuPhiKSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThuPhiKSKActionPerformed(evt);
            }
        });
        mnuVienPhi.add(mnuThuPhiKSK);

        mnuListDaThu.setText("Danh sách KSK đã thu...");
        mnuVienPhi.add(mnuListDaThu);
        mnuVienPhi.add(jSeparator2);

        mnuThuPhiCQ.setText("Thu phí khám sức khoẻ cơ quan...");
        mnuVienPhi.add(mnuThuPhiCQ);

        mnuListThuCQ.setText("Danh sách thu phí KSK cơ quan...");
        mnuVienPhi.add(mnuListThuCQ);
        mnuVienPhi.add(jSeparator4);

        mnuGiaVP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/LegendHS.png"))); // NOI18N
        mnuGiaVP.setText("Khai báo giá viện phí...");
        mnuGiaVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGiaVPActionPerformed(evt);
            }
        });
        mnuVienPhi.add(mnuGiaVP);

        mnuGoiGiaVP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/MultiplePagesHS.png"))); // NOI18N
        mnuGoiGiaVP.setText("Tạo gói giá viện phí...");
        mnuGoiGiaVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGoiGiaVPActionPerformed(evt);
            }
        });
        mnuVienPhi.add(mnuGoiGiaVP);
        mnuVienPhi.add(jSeparator3);

        mnuListThuNgan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PackageKSK/Images/List_BulletsHS.png"))); // NOI18N
        mnuListThuNgan.setText("Khai báo Thu ngân...");
        mnuListThuNgan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListThuNganActionPerformed(evt);
            }
        });
        mnuVienPhi.add(mnuListThuNgan);

        mainMenu.add(mnuVienPhi);

        mnuBaoCao.setText("Báo cáo");

        mnuTKHoanTra.setText("Thống kê số lao động nước ngoài trả về...");
        mnuBaoCao.add(mnuTKHoanTra);

        mainMenu.add(mnuBaoCao);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addGap(8, 8, 8)
                .addComponent(lblUserName))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        lblUserName.setText("Administrator");
    }//GEN-LAST:event_formWindowOpened

    private void mnuCoQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCoQuanActionPerformed
        JDialogCoQuan frm = new JDialogCoQuan(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCoQuanActionPerformed

    private void mnuLyDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLyDoActionPerformed
        JDialogLyDo frm = new JDialogLyDo(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuLyDoActionPerformed

    private void mnuQuocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuocGiaActionPerformed
        JDialogQuocGia frm = new JDialogQuocGia(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuQuocGiaActionPerformed

    private void mnuDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangKyActionPerformed
        JDialogGiayDK frm = new JDialogGiayDK(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuDangKyActionPerformed

    private void mnuListDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListDKActionPerformed
        try {
            JInternalFrameListGiayKSK frm = new JInternalFrameListGiayKSK();
            jDesktopPane1.add(frm);
            frm.setMaximum(true);
            frm.setVisible(true);
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_mnuListDKActionPerformed

    private void mnuGiaVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGiaVPActionPerformed
        JDialogGiaVP frm = new JDialogGiaVP(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuGiaVPActionPerformed

    private void mnuGoiGiaVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGoiGiaVPActionPerformed
        JDialogGoiGiaVP frm = new JDialogGoiGiaVP(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuGoiGiaVPActionPerformed

    private void mnuListThuNganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListThuNganActionPerformed
        JDialogThuNgan frm = new JDialogThuNgan(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuListThuNganActionPerformed

    private void mnuThuPhiKSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThuPhiKSKActionPerformed
        JDialogThuPhiKSK frm = new JDialogThuPhiKSK(this, true);
        frm.setSoKSK("2014000005");
        frm.setVisible(true);
    }//GEN-LAST:event_mnuThuPhiKSKActionPerformed

    private void mnuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameKSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameKSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameKSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameKSK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameKSK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu mnuBaoCao;
    private javax.swing.JMenuItem mnuCoQuan;
    private javax.swing.JMenuItem mnuCreateUsers;
    private javax.swing.JMenuItem mnuDangKy;
    private javax.swing.JMenu mnuDanhMuc;
    private javax.swing.JMenuItem mnuDoiMK;
    private javax.swing.JMenuItem mnuGiaVP;
    private javax.swing.JMenuItem mnuGoiGiaVP;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuHoanTra;
    private javax.swing.JMenu mnuKSK;
    private javax.swing.JMenuItem mnuListDK;
    private javax.swing.JMenuItem mnuListDaThu;
    private javax.swing.JMenuItem mnuListThuCQ;
    private javax.swing.JMenuItem mnuListThuNgan;
    private javax.swing.JMenuItem mnuLogOut;
    private javax.swing.JMenuItem mnuLyDo;
    private javax.swing.JMenuItem mnuPhanQuyen;
    private javax.swing.JMenuItem mnuQuit;
    private javax.swing.JMenuItem mnuQuocGia;
    private javax.swing.JMenuItem mnuTKHoanTra;
    private javax.swing.JMenuItem mnuThuPhiCQ;
    private javax.swing.JMenuItem mnuThuPhiKSK;
    private javax.swing.JMenu mnuVienPhi;
    // End of variables declaration//GEN-END:variables
}
